name: CI/CD Pipeline - Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        working-directory: project     
        run: mvn clean package -DskipTests

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/gcp_vm_key
          chmod 600 ~/.ssh/gcp_vm_key
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to GCP VM
        run: |
          # Copy jar from project/target
          scp -i ~/.ssh/gcp_vm_key project/target/*.jar borislav_tomov@${{ secrets.GCP_VM_IP }}:/home/borislav_tomov/app-prod/app.jar
          # Restart app on remote VM
          ssh -i ~/.ssh/gcp_vm_key borislav_tomov@${{ secrets.GCP_VM_IP }} << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar /home/borislav_tomov/app-prod/app.jar > /home/borislav_tomov/app-prod/app.log 2>&1 &
          EOF
