name: Java CI/CD to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./project

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-artifact
          path: project/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app-artifact

    
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: borislav_tomov
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          source: 'project-0.0.1-SNAPSHOT.jar'
          target: '/home/borislav_tomov/app-prod/'
          #debug: true
          script: |
            # Stop the old application
            sudo systemctl stop project-0.0.1-SNAPSHOT.service || true

            # Remove old jar file
            rm -f /home/borislav_tomov/app-prod/project-0.0.1-SNAPSHOT.jar
            
            # Restart the application as a service
            sudo systemctl start project-0.0.1-SNAPSHOT.service

   
